### ISSUE TITLE
python-3.9.0-embed-amd64 用pip安装失败(包括aliyun-python-sdk-core和aliyun-python-sdk-iot)

### ISSUE THREAD

**Issue by ghost** [duangy/aliyunsdkcore#9]
pip install aliyunsdkcore 
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/ 
 Collecting aliyunsdkcore
Downloading 
http://mirrors.aliyun.com/pypi/packages/36/80/4fd3153ce15ec7edae283fa937ee1adc0855f980ce248611b2e009d343df/aliyunsdkcore-1.0.3.tar.gz (23 kB)                                                                                        
 ERROR: Command errored out with exit status 1:                                                                          
 command: 'd:\python-3.9.0-embed-amd64\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-vc5sofny\\aliyunsdkcore_760263d2c4f3402088d9f8592997f656\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-vc5sofny\\aliyunsdkcore_760263d2c4f3402088d9f8592997f656\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Admin\AppData\Local\Temp\pip-pip-egg-info-lpu5ujkl'                                                                                              
 cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-vc5sofny\aliyunsdkcore_760263d2c4f3402088d9f8592997f656\       
 Complete output (5 lines):                                                                                             
 Traceback (most recent call last):                                                                                       
 File "<string>", line 1, in <module>                                                                                    
File "C:\Users\Admin\AppData\Local\Temp\pip-install-vc5sofny\aliyunsdkcore_760263d2c4f3402088d9f8592997f656\setup.py", line 225, in <module>                                                                                                      
VERSION = __import__(PACKAGE).__version__                                                                           
ModuleNotFoundError: No module named 'aliyunsdkcore'                                                                   
 ----------------------------------------                                                                           
 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by tietang** [comment]
同样的问题：

 ..\..\..\python_embeded\python.exe -s -m pip install  aliyun-python-sdk-core-v3
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting aliyun-python-sdk-core-v3
  Using cached https://mirrors.aliyun.com/pypi/packages/50/31/bdf3eba750e9d7213248efea30ad29a62f2d449607e03f538d4d9455d952/aliyun-python-sdk-core-v3-2.13.33.tar.gz (440 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\hy\AppData\Local\Temp\pip-install-8h1o9jtn\aliyun-python-sdk-core-v3_b3b53e839d294ab3a6db7c270572cd49\setup.py", line 41, in <module>
          VERSION = __import__(PACKAGE).__version__
                    ^^^^^^^^^^^^^^^^^^^
      ModuleNotFoundError: No module named 'aliyunsdkcore'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by geekil** [comment]
@tietang 
[阿里云python sdk最新文档地址](https://help.aliyun.com/zh/sdk/developer-reference/v2-python-integrated-sdk?spm=a2c4g.11186623.0.0.3c15795et8ipN5)

阿里将sdk接入分为特化调用和泛化调用，特化调用安装地址为：

```pip install alibabacloud_dysmsapi20170525==2.0.24```,

泛化地址为：

```pip install alibabacloud-tea-openapi```

**Comment by tietang** [comment]
同样的问题， python_embeded 环境一样安装不了

**Comment by Jack-919** [comment]
> [阿里云python sdk最新文档地址](https://help.aliyun.com/zh/sdk/developer-reference/v2-python-integrated-sdk?spm=a2c4g.11186623.0.0.3c15795et8ipN5)
> 
> 阿里将sdk接入分为特化调用和泛化调用，特化调用安装地址为：
> 
> `pip install alibabacloud_dysmsapi20170525==2.0.24`,
> 
> 泛化地址为：
> 
> `pip install alibabacloud-tea-openapi`这两种方法都不行，现在报错是 ModuleNotFoundError: No module named 'alibabacloud_tea_openapi'

**Comment by geekil** [comment]
@Jack-919 [pypi地址](https://pypi.org/project/alibabacloud-tea-openapi/) 你看看你的环境和python版本

**Comment by nicklhy** [comment]
Same problem here. Got this bug when pip install oss2 with comfyui windows version
